# pineconemc: fork de Prism Launcher con soporte Ely.by (Qt6).
# AUR elyprismlauncher-bin: reempaqueta el pkg.tar.zst oficial,
# precompilado. (El paquete se llama por el binario, no por la app.)
name: pineconemc
source:
  type: aur
  pkg: elyprismlauncher-bin
bin: /usr/bin/elyprismlauncher
icon: /usr/share/icons/hicolor/scalable/apps/io.github.elyprismlauncher.ElyPrismLauncher.svg
desktop: /usr/share/applications/io.github.elyprismlauncher.ElyPrismLauncher.desktop
debloat: mesa
